---
- name: "Copy bashrc"
  copy:
    src: "{{ role_path }}/files/bashrc"
    dest: "{{ ansible_env.HOME }}/.bashrc"

- name: "Install packages for env - Rust„ÄÅGo"
  pacman:
    name:
      - rust
      - go
    state: latest
  become: true
  become_method: sudo